import numpy as np
un_array =np.empty(shape=(2,3))
print("uninitilized array:")
print("un_array")
ones_array = np.ones(shape=(2,3))
print("Array with All Elements as 1:")
print(ones_array)
zeros_array = np.zeros(shape=(2, 3))
print("Array with All Elements as 0:")
print(zeros_array)